# Menggunakan image Python versi ringan
FROM python:3.10-slim

# Menentukan direktori kerja di dalam container
WORKDIR /app

# Menyalin seluruh file (yang sekarang HANYA berisi file backend)
COPY . .

# Menginstal dependensi (langsung memanggil nama file karena sudah satu ruangan)
RUN pip install --no-cache-dir -r requirements.txt

# Mengekspos port 7860
EXPOSE 7860

# Menjalankan server FastAPI (langsung memanggil nama file backend.py)
CMD ["uvicorn", "backend:app", "--host", "0.0.0.0", "--port", "7860"]